polygon:
  api_key: ${env:POLYGON_API_KEY}
cache:
  root: ./data/csv
  interval: 1D

features:
  indicators: [SMA, EMA, RSI, MACD, BollingerBands, ATR]
  sma_windows: [10, 20, 50]
  ema_windows: [10, 20, 50]
  rsi_window: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bb_window: 20
  bb_std: 2
  lags: [1, 2, 3, 5]
  rolling_windows: [5, 10, 20]

ml:
  target: next_return
  test_size: 0.2
  models: [RandomForest, XGBoost, LightGBM]

advanced_features:
  crossasset: true
  volatility: true
  options_implied: true
  selection: true
crossasset:
  benchmarks: [SPY, QQQ, VIX]
  corr_windows: [20, 60]
volatility:
  windows: [10, 20, 60]
selection:
  pca_components: 5
