name: OAMI CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Lint
        run: |
          flake8 src tests || true
          black --check src tests || true
      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings --cov=src/oami --cov-report=term-missing -q
